Controllers/RestSharpTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CSharp_Scraper.Models;

namespace CSharp_Scraper.Controllers
{
    public class RestSharpTablesController : Controller
    {
        private RestSharpTableEntities db = new RestSharpTableEntities();

        // GET: RestSharpTables
        public async Task<ActionResult> Index()
        {
            return View(await db.RestSharpTables.ToListAsync());
        }

        // GET: RestSharpTables/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RestSharpTable restSharpTable = await db.RestSharpTables.FindAsync(id);
            if (restSharpTable == null)
            {
                return HttpNotFound();
            }
            return View(restSharpTable);
        }

        // GET: RestSharpTables/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RestSharpTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,TimeScraped,Symbol,LastPrice,Change,ChangePercent")] RestSharpTable restSharpTable)
        {
            if (ModelState.IsValid)
            {
                db.RestSharpTables.Add(restSharpTable);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(restSharpTable);
        }

        // GET: RestSharpTables/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RestSharpTable restSharpTable = await db.RestSharpTables.FindAsync(id);
            if (restSharpTable == null)
            {
                return HttpNotFound();
            }
            return View(restSharpTable);
        }

        // POST: RestSharpTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,TimeScraped,Symbol,LastPrice,Change,ChangePercent")] RestSharpTable restSharpTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restSharpTable).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(restSharpTable);
        }

        // GET: RestSharpTables/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RestSharpTable restSharpTable = await db.RestSharpTables.FindAsync(id);
            if (restSharpTable == null)
            {
                return HttpNotFound();
            }
            return View(restSharpTable);
        }

        // POST: RestSharpTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            RestSharpTable restSharpTable = await db.RestSharpTables.FindAsync(id);
            db.RestSharpTables.Remove(restSharpTable);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult NewApiCall()
        {
            ApiCall newScrape = new ApiCall();
            newScrape.RestScrape();

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult DeleteTable()
        {
            string deleteQuery = "DELETE FROM RestSharpTable;" + "DBCC CHECKIDENT (RestSharpTable, RESEED, 0);";

            db.Database.ExecuteSqlCommand(deleteQuery);

            return RedirectToAction("Index");

        }
    }
}

Views/RestSharpTables/Create.cshtml
@model CSharp_Scraper.Models.RestSharpTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>RestSharpTable</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.TimeScraped, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TimeScraped, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TimeScraped, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Symbol, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Symbol, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Symbol, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LastPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastPrice, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastPrice, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ChangePercent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChangePercent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChangePercent, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/RestSharpTables/Delete.cshtml
@model CSharp_Scraper.Models.RestSharpTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>RestSharpTable</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TimeScraped)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TimeScraped)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Symbol)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Symbol)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LastPrice)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LastPrice)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangePercent)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangePercent)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/RestSharpTables/Details.cshtml
@model CSharp_Scraper.Models.RestSharpTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>RestSharpTable</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TimeScraped)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TimeScraped)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Symbol)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Symbol)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LastPrice)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LastPrice)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangePercent)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangePercent)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/RestSharpTables/Edit.cshtml
@model CSharp_Scraper.Models.RestSharpTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>RestSharpTable</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.TimeScraped, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TimeScraped, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TimeScraped, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Symbol, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Symbol, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Symbol, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LastPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastPrice, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastPrice, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ChangePercent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChangePercent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChangePercent, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/RestSharpTables/Index.cshtml
@model IEnumerable<CSharp_Scraper.Models.RestSharpTable>

@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MorningStar Finance Scrape Database</title>
</head>
<body>
    <div class="del-database col-md-6">
        <h2>Delete Database</h2>
        <button type="submit" class="btn btn-info m-auto" value="Most Recent Scrape" onclick="location.href='@Url.Action("MostRecentScrape", "RestSharpTables")'">Latest Scrape Data</button>
    </div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TimeScraped)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Symbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Change)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChangePercent)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeScraped)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Symbol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Change)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChangePercent)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</body>
</html>