Controllers/HAPStockTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CSharp_Scraper.Models;

namespace CSharp_Scraper.Controllers
{
    public class HAPStockTablesController : Controller
    {
        private HAPStockTableEntities db = new HAPStockTableEntities();

        // GET: HAPStockTables
        public async Task<ActionResult> Index()
        {
            return View(await db.HAPStockTables.ToListAsync());
        }

        // GET: HAPStockTables/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HAPStockTable hAPStockTable = await db.HAPStockTables.FindAsync(id);
            if (hAPStockTable == null)
            {
                return HttpNotFound();
            }
            return View(hAPStockTable);
        }

        // GET: HAPStockTables/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HAPStockTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Time_Scraped,Stock_Symbol,Last_Price,Change,Change_Percent")] HAPStockTable hAPStockTable)
        {
            if (ModelState.IsValid)
            {
                db.HAPStockTables.Add(hAPStockTable);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(hAPStockTable);
        }

        // GET: HAPStockTables/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HAPStockTable hAPStockTable = await db.HAPStockTables.FindAsync(id);
            if (hAPStockTable == null)
            {
                return HttpNotFound();
            }
            return View(hAPStockTable);
        }

        // POST: HAPStockTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Time_Scraped,Stock_Symbol,Last_Price,Change,Change_Percent")] HAPStockTable hAPStockTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hAPStockTable).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(hAPStockTable);
        }

        // GET: HAPStockTables/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HAPStockTable hAPStockTable = await db.HAPStockTables.FindAsync(id);
            if (hAPStockTable == null)
            {
                return HttpNotFound();
            }
            return View(hAPStockTable);
        }

        // POST: HAPStockTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            HAPStockTable hAPStockTable = await db.HAPStockTables.FindAsync(id);
            db.HAPStockTables.Remove(hAPStockTable);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult HAPScrape()
        {
            HAPScrape scrape = new HAPScrape();
            scrape.Scrape();

            return RedirectToAction("Index");
        }


        [Authorize]
        public ActionResult DeleteTable()
        {
            string deleteQuery = "DELETE FROM HAPStockTable;" + "DBCC CHECKIDENT (HAPStockTable, RESEED, 0);";

            db.Database.ExecuteSqlCommand(deleteQuery);

            return RedirectToAction("Index");

        }
    }
}

Views/HAPStockTables/Create.cshtml
@model CSharp_Scraper.Models.HAPStockTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>HAPStockTable</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Time_Scraped, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Time_Scraped, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Time_Scraped, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Stock_Symbol, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Stock_Symbol, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Stock_Symbol, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Last_Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Last_Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Last_Price, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change_Percent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change_Percent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change_Percent, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/HAPStockTables/Delete.cshtml
@model CSharp_Scraper.Models.HAPStockTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>HAPStockTable</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Time_Scraped)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Time_Scraped)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Stock_Symbol)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Stock_Symbol)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Last_Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Last_Price)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change_Percent)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change_Percent)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/HAPStockTables/Details.cshtml
@model CSharp_Scraper.Models.HAPStockTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>HAPStockTable</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Time_Scraped)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Time_Scraped)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Stock_Symbol)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Stock_Symbol)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Last_Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Last_Price)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change_Percent)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change_Percent)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/HAPStockTables/Edit.cshtml
@model CSharp_Scraper.Models.HAPStockTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>HAPStockTable</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Time_Scraped, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Time_Scraped, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Time_Scraped, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Stock_Symbol, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Stock_Symbol, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Stock_Symbol, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Last_Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Last_Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Last_Price, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change_Percent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change_Percent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change_Percent, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/HAPStockTables/Index.cshtml
@model IEnumerable<CSharp_Scraper.Models.HAPStockTable>

@{
    ViewBag.Title = "Home Page";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MarketWatch Scrape History Table</title>
</head>
<body>
    <div class="del-database col-md-6">
        <h2>Most Recent Database Scrape</h2>
        <button type="submit" class="btn btn-info margin-" value="Most Recent Scrape" onclick="location.href='@Url.Action("MostRecentScrape", "HAPStockTables")'">Latest Scrape Data</button>
    </div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Time_Scraped)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock_Symbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Last_Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Change)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Change_Percent)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Time_Scraped)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock_Symbol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Last_Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Change)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Change_Percent)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</body>
</html>