Controllers/StockTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;

namespace CSharp_Scraper.Controllers
{
    public class StockTablesController : Controller
    {
        private StockTableEntities db = new StockTableEntities();

        public async Task<ActionResult> Index()
        {
            return View(await db.StockTables.ToListAsync());
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StockTable stockTable = await db.StockTables.FindAsync(id);
            if (stockTable == null)
            {
                return HttpNotFound();
            }
            return View(stockTable);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Time_Scraped,Stock_Symbol,Last_Price,Change,Change_Percent,Volume,Shares,Average_Volume,Market_Cap")] StockTable stockTable)
        {
            if (ModelState.IsValid)
            {
                db.StockTables.Add(stockTable);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(stockTable);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StockTable stockTable = await db.StockTables.FindAsync(id);
            if (stockTable == null)
            {
                return HttpNotFound();
            }
            return View(stockTable);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Time_Scraped,Stock_Symbol,Last_Price,Change,Change_Percent,Volume,Shares,Average_Volume,Market_Cap")] StockTable stockTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stockTable).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(stockTable);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StockTable stockTable = await db.StockTables.FindAsync(id);
            if (stockTable == null)
            {
                return HttpNotFound();
            }
            return View(stockTable);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            StockTable stockTable = await db.StockTables.FindAsync(id);
            db.StockTables.Remove(stockTable);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult Scrape()
        {
            var scrape = new Scrape("milomacphail@gmail.com", "Pandahead1");

            scrape.Login();
            scrape.Navigate();
            scrape.ScrapeTable();

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult DeleteTable()
        {
            string deleteQuery = "DELETE FROM StockTable;" + "DBCC CHECKIDENT (StockTable, RESEED, 0);";

            db.Database.ExecuteSqlCommand(deleteQuery);

            return RedirectToAction("Index");
        }

        [Authorize]

        public ActionResult MostRecentScrape()
        {
            string recentQuery = "SELECT Id, MAX (time_scraped) FROM dbo.StockTable GROUP BY Id";
            db.Database.ExecuteSqlCommand(recentQuery);
            return RedirectToAction("Index");
        }
    }
}

Views/StockTables/Create.cshtml
@model CSharp_Scraper.StockTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>StockTable</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Time_Scraped, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Time_Scraped, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Time_Scraped, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Stock_Symbol, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Stock_Symbol, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Stock_Symbol, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Last_Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Last_Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Last_Price, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change_Percent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change_Percent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change_Percent, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Volume, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Volume, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Volume, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Shares, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Shares, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Shares, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Average_Volume, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Average_Volume, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Average_Volume, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Market_Cap, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Market_Cap, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Market_Cap, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/StockTables/Delete.cshtml
@model CSharp_Scraper.StockTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>StockTable</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Time_Scraped)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Time_Scraped)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Stock_Symbol)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Stock_Symbol)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Last_Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Last_Price)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change_Percent)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change_Percent)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Volume)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Volume)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Shares)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Shares)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Average_Volume)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Average_Volume)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Market_Cap)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Market_Cap)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/StockTables/Details.cshtml
@model CSharp_Scraper.StockTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>StockTable</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Time_Scraped)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Time_Scraped)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Stock_Symbol)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Stock_Symbol)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Last_Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Last_Price)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Change_Percent)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Change_Percent)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Volume)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Volume)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Shares)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Shares)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Average_Volume)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Average_Volume)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Market_Cap)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Market_Cap)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/StockTables/Edit.cshtml
@model CSharp_Scraper.StockTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>StockTable</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Time_Scraped, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Time_Scraped, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Time_Scraped, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Stock_Symbol, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Stock_Symbol, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Stock_Symbol, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Last_Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Last_Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Last_Price, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Change_Percent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Change_Percent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Change_Percent, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Volume, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Volume, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Volume, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Shares, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Shares, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Shares, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Average_Volume, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Average_Volume, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Average_Volume, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Market_Cap, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Market_Cap, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Market_Cap, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/StockTables/Index.cshtml
@model IEnumerable<CSharp_Scraper.StockTable>

@{
     ViewBag.Title = "Home Page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Yahoo Finance Stock Scrape History</title>
</head>
<body>
    <div class="del-database col-md-6">
        <h2>Delete Database</h2>
        <button type="submit" class="btn btn-info" value="Most Recent Scrape" onclick="location.href='@Url.Action("MostRecentScrape", "StockTables")'">Latest Scrape Data</button>
    </div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Time_Scraped)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock_Symbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Last_Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Change)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Change_Percent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Volume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Shares)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Average_Volume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Market_Cap)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Time_Scraped)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock_Symbol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Last_Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Change)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Change_Percent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Volume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Shares)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Average_Volume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Market_Cap)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</body>
</html>

Views/StockTables/Scrape.cshtml
@model IEnumerable<CSharp_Scraper.StockTable>

@{
     ViewBag.Title = "Home Page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Time_Scraped)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock_Symbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Last_Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Change)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Change_Percent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Volume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Shares)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Average_Volume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Market_Cap)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Time_Scraped)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock_Symbol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Last_Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Change)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Change_Percent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Volume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Shares)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Average_Volume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Market_Cap)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</body>
</html>